services:
  - type: web
    name: etsy-listing-studio-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ETSY_API_KEY
        sync: false
      - key: ETSY_SHARED_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://hafeez45d.github.io/etsy-listing-studio/
      - key: ENCRYPTION_SECRET
        generateValue: true
